 {{
    config(
        materialized='incremental'
    )
}}

with stg as (
    select
    CXKEY_TEST_NM as TEST_NM,
	TEST_ST_TIME,
	TEST_END_TIME,
	STTN_NM,
	REPRT_NM,
	CXKEY_RESLT_TYP as RESLT_TYP,
	COVERAGE_FACTOR as ADJSTD_CVRG_FACTOR,
	LMTED_TUR,
	FIRMWARE_VER,
	WRK_CENTER_ID,
	APP_VER_NUM,
	CXKEY_APP_ID as APP_ID,
	CXKEY_APP_PLATFORM as APP_PLATFORM,
	NEAR_SPCFCTN_LMT_IND,
	NEAR_GURDBD_LMT_IND,
	CAL_TEST_DATA_TYP_ID,
	ASRECDORCOMP_DATA_IND as DI,
	UNCRTNTY_STAT_VAL,
	RPRTD_JDGMNT,
	STD_JDGMNT,
	GURDBD_JDGMNT,
	PRCSS_JDGMNT,
	INSERT_DT,
	UPD_DT,
	CXKEY_SRVC_ORD_NUM,
	LAST_MODIFIED_DT,
	CXKEY_CAL_PROCEDURE_ID,
	CXKEY_MFGR_ID,
	CXKEY_MFGR_MDL_NUM,
	CXKEY_SR_NUM,
	CXKEY_FRMWRK_ID,
	CXKEY_SUBMITTING_ENTITY,
	RESLT_TYP_DATAIS_COPY,
	CAL_TEST_RESLT_RPRTD_JDGMNT,
	CAL_TEST_RESLT_STD_JDGMNT,
	CAL_TEST_RESLT_GURDBD_JDGMNT,
	CAL_TEST_RESLT_PRCSS_JDGMNT,
	CAL_TST_RSLT_NR_SPFTN_LMT_IND,
	CAL_TST_RSLT_NR_GRDBD_LMT_IND,
	AS_CMP_TEST_NM,
	AS_CMP_TEST_ST_TIME,
	AS_CMP_TEST_END_TIME,
	AS_CMP_STTN_NM,
	AS_CMP_REPRT_NM,
	AS_CMP_WRK_CENTER_ID,
	AS_CMP_LMTED_TUR,
	AS_CMP_FIRMWARE_VER,
	AS_CMP_APP_VER_NUM,
	AS_CMP_APP_ID,
	AS_CMP_APP_PLATFORM,
	AS_CMP_UNCNTRTY_STAT_VAL as AS_CMP_UNCRTNTY_STAT_VAL,
	AS_CMP_RPRTD_JDGMNT,
	AS_CMP_STD_JDGMNT,
	AS_CMP_GURDBD_JDGMNT,
	AS_CMP_PRCSS_JDGMNT,
	AS_CMP_NEAR_SPCFCTN_LMT_IND,
	AS_CMP_NEAR_GURDBD_LMT_IND,
	AS_CMP_ADJ_COVERAGE_FACTOR as AS_CMP_ADJSTD_CVRG_FACTOR,
	AS_CMP_CAL_TST_RPRTD_JDGMNT,
	AS_CMP_CAL_TST_STD_JDGMNT,
	AS_CMP_CAL_TST_GURDBD_JDGMNT,
	AS_CMP_CAL_TST_PRCSS_JDGMNT,
	AS_CMP_CAL_TST_NR_SPTN_LT_IND as AS_CMP_CAL_TST_NEAR_SPCFCTN_LMT_IND,
	AS_CMP_CAL_TST_NR_GDBD_LMT_IND as AS_CMP_CAL_TST_NEAR_GURDBD_LMT_IND
    from CA_ASRECDORCOMP_DATA_TYP_STG
),

expr_111 as (
    select
	DI,
    RESLT_TYP,
    case
        when
            (
                RESLT_TYP = 'AS_RECEIVED'
            )
        then 'R'
        else 'C'
    end as RT,
   CASE 
   WHEN DI = 'R' THEN
      CASE 
         WHEN RT = 'R' THEN TEST_NM
         WHEN AS_CMP_CAL_TST_RPRTD_JDGMNT = 'NOT_DONE' OR AS_CMP_CAL_TST_RPRTD_JDGMNT = 'UNKNOWN' OR AS_CMP_CAL_TST_RPRTD_JDGMNT IS NULL THEN TEST_NM
         ELSE AS_CMP_TEST_NM
      END
   WHEN DI = 'C' THEN
      CASE 
         WHEN RT = 'C' THEN AS_CMP_TEST_NM
         WHEN CAL_TEST_RESLT_RPRTD_JDGMNT = 'NOT_DONE' OR CAL_TEST_RESLT_RPRTD_JDGMNT = 'UNKNOWN' OR CAL_TEST_RESLT_RPRTD_JDGMNT IS NULL THEN AS_CMP_TEST_NM
         ELSE TEST_NM
      END
   WHEN DI = 'A' OR DI = 'X' THEN
      CASE 
         WHEN RT = 'R' THEN TEST_NM
         ELSE AS_CMP_TEST_NM
      END
   ELSE
      TEST_NM
   END AS TEST_NM,
  
  CASE 
   WHEN DI = 'R' THEN
      CASE 
         WHEN RT = 'R' THEN TEST_ST_TIME
         WHEN AS_CMP_CAL_TST_RPRTD_JDGMNT = 'NOT_DONE' OR AS_CMP_CAL_TST_RPRTD_JDGMNT = 'UNKNOWN' OR AS_CMP_CAL_TST_RPRTD_JDGMNT IS NULL THEN TEST_ST_TIME
         ELSE AS_CMP_TEST_ST_TIME
      END
   WHEN DI = 'C' THEN
      CASE 
         WHEN RT = 'C' THEN AS_CMP_TEST_ST_TIME
         WHEN CAL_TEST_RESLT_RPRTD_JDGMNT = 'NOT_DONE' OR CAL_TEST_RESLT_RPRTD_JDGMNT = 'UNKNOWN' OR CAL_TEST_RESLT_RPRTD_JDGMNT IS NULL THEN AS_CMP_TEST_ST_TIME
         ELSE TEST_ST_TIME
      END
   WHEN DI = 'A' OR DI = 'X' THEN
      CASE 
         WHEN RT = 'R' THEN TEST_ST_TIME
         ELSE AS_CMP_TEST_ST_TIME
      END
   ELSE
      TEST_ST_TIME
   END AS TEST_ST_TIME,
  
  
   CASE 
   WHEN DI = 'R' THEN
      CASE 
         WHEN RT = 'R' THEN TEST_END_TIME
         WHEN AS_CMP_CAL_TST_RPRTD_JDGMNT = 'NOT_DONE' OR AS_CMP_CAL_TST_RPRTD_JDGMNT = 'UNKNOWN' OR AS_CMP_CAL_TST_RPRTD_JDGMNT IS NULL THEN TEST_END_TIME
         ELSE AS_CMP_TEST_END_TIME
      END
   WHEN DI = 'C' THEN
      CASE 
         WHEN RT = 'C' THEN AS_CMP_TEST_END_TIME
         WHEN CAL_TEST_RESLT_RPRTD_JDGMNT = 'NOT_DONE' OR CAL_TEST_RESLT_RPRTD_JDGMNT = 'UNKNOWN' OR CAL_TEST_RESLT_RPRTD_JDGMNT IS NULL THEN AS_CMP_TEST_END_TIME
         ELSE TEST_END_TIME
      END
   WHEN DI = 'A' OR DI = 'X' THEN
      CASE 
         WHEN RT = 'R' THEN TEST_END_TIME
         ELSE AS_CMP_TEST_END_TIME
      END
   ELSE
      TEST_END_TIME
   END AS TEST_END_TIME,
  
   CASE 
   WHEN DI = 'R' THEN
      CASE 
         WHEN RT = 'R' THEN STTN_NM
         WHEN AS_CMP_CAL_TST_RPRTD_JDGMNT = 'NOT_DONE' OR AS_CMP_CAL_TST_RPRTD_JDGMNT = 'UNKNOWN' OR AS_CMP_CAL_TST_RPRTD_JDGMNT IS NULL THEN STTN_NM
         ELSE AS_CMP_STTN_NM
      END
   WHEN DI = 'C' THEN
      CASE 
         WHEN RT = 'C' THEN AS_CMP_STTN_NM
         WHEN CAL_TEST_RESLT_RPRTD_JDGMNT = 'NOT_DONE' OR CAL_TEST_RESLT_RPRTD_JDGMNT = 'UNKNOWN' OR CAL_TEST_RESLT_RPRTD_JDGMNT IS NULL THEN AS_CMP_STTN_NM
         ELSE STTN_NM
      END
   WHEN DI = 'A' OR DI = 'X' THEN
      CASE 
         WHEN RT = 'R' THEN STTN_NM
         ELSE AS_CMP_STTN_NM
      END
   ELSE
      STTN_NM
   END as STTN_NM,

    CASE 
    WHEN DI = 'R' THEN 
        CASE 
            WHEN RT = 'R' THEN REPRT_NM
            WHEN AS_CMP_CAL_TST_RPRTD_JDGMNT = 'NOT_DONE' or AS_CMP_CAL_TST_RPRTD_JDGMNT = 'UNKNOWN' OR AS_CMP_CAL_TST_RPRTD_JDGMNT IS NULL THEN REPRT_NM
            ELSE AS_CMP_REPRT_NM
        END
    WHEN DI = 'C' THEN 
        CASE 
            WHEN RT = 'C' THEN AS_CMP_REPRT_NM
            WHEN CAL_TEST_RESLT_RPRTD_JDGMNT = 'NOT_DONE' OR CAL_TEST_RESLT_RPRTD_JDGMNT = 'UNKNOWN' OR CAL_TEST_RESLT_RPRTD_JDGMNT IS NULL THEN AS_CMP_REPRT_NM
            ELSE REPRT_NM
        END
    WHEN DI = 'A' OR DI = 'X' THEN
        CASE 
            WHEN RT = 'R' THEN REPRT_NM
            ELSE AS_CMP_REPRT_NM
        END
    ELSE 
        REPRT_NM
    END AS REPRT_NM,
  
    CASE 
    WHEN DI = 'R' THEN 
        CASE 
            WHEN RT = 'R' THEN ADJSTD_CVRG_FACTOR
            WHEN AS_CMP_CAL_TST_RPRTD_JDGMNT = 'NOT_DONE' or AS_CMP_CAL_TST_RPRTD_JDGMNT = 'UNKNOWN' OR AS_CMP_CAL_TST_RPRTD_JDGMNT IS NULL THEN ADJSTD_CVRG_FACTOR
            ELSE AS_CMP_ADJSTD_CVRG_FACTOR
        END
    WHEN DI = 'C' THEN 
        CASE 
            WHEN RT = 'C' THEN AS_CMP_ADJSTD_CVRG_FACTOR
            WHEN CAL_TEST_RESLT_RPRTD_JDGMNT = 'NOT_DONE' OR CAL_TEST_RESLT_RPRTD_JDGMNT = 'UNKNOWN' OR CAL_TEST_RESLT_RPRTD_JDGMNT IS NULL THEN AS_CMP_ADJSTD_CVRG_FACTOR
            ELSE ADJSTD_CVRG_FACTOR
        END
    WHEN DI = 'A' OR DI = 'X' THEN
        CASE 
            WHEN RT = 'R' THEN ADJSTD_CVRG_FACTOR
            ELSE AS_CMP_ADJSTD_CVRG_FACTOR
        END
    ELSE 
        ADJSTD_CVRG_FACTOR
    END AS ADJSTD_CVRG_FACTOR,
  
   CASE 
    WHEN DI = 'R' THEN 
        CASE 
            WHEN RT = 'R' THEN LMTED_TUR
            WHEN AS_CMP_CAL_TST_RPRTD_JDGMNT = 'NOT_DONE' OR AS_CMP_CAL_TST_RPRTD_JDGMNT = 'UNKNOWN' OR AS_CMP_CAL_TST_RPRTD_JDGMNT IS NULL THEN LMTED_TUR
            ELSE AS_CMP_LMTED_TUR
        END
    WHEN DI = 'C' THEN 
        CASE 
            WHEN RT = 'C' THEN AS_CMP_LMTED_TUR
            WHEN CAL_TEST_RESLT_RPRTD_JDGMNT = 'NOT_DONE' OR CAL_TEST_RESLT_RPRTD_JDGMNT = 'UNKNOWN' OR CAL_TEST_RESLT_RPRTD_JDGMNT IS NULL THEN AS_CMP_LMTED_TUR
            ELSE LMTED_TUR
        END
    WHEN DI = 'A' OR DI = 'X' THEN 
        CASE 
            WHEN RT = 'R' THEN LMTED_TUR
            ELSE AS_CMP_LMTED_TUR
        END
    ELSE LMTED_TUR
    END as LMTED_TUR,
  
    CASE 
    WHEN DI = 'R' THEN 
        CASE 
            WHEN RT = 'R' THEN FIRMWARE_VER
            WHEN AS_CMP_CAL_TST_RPRTD_JDGMNT = 'NOT_DONE' or AS_CMP_CAL_TST_RPRTD_JDGMNT = 'UNKNOWN' OR AS_CMP_CAL_TST_RPRTD_JDGMNT IS NULL THEN FIRMWARE_VER
            ELSE AS_CMP_FIRMWARE_VER
        END
    WHEN DI = 'C' THEN 
        CASE 
            WHEN RT = 'C' THEN AS_CMP_FIRMWARE_VER
            WHEN CAL_TEST_RESLT_RPRTD_JDGMNT = 'NOT_DONE' OR CAL_TEST_RESLT_RPRTD_JDGMNT = 'UNKNOWN' OR CAL_TEST_RESLT_RPRTD_JDGMNT IS NULL THEN AS_CMP_FIRMWARE_VER
            ELSE FIRMWARE_VER
        END
    WHEN DI = 'A' OR DI = 'X' THEN
        CASE 
            WHEN RT = 'R' THEN FIRMWARE_VER
            ELSE AS_CMP_FIRMWARE_VER
        END
    ELSE 
        FIRMWARE_VER
    END AS FIRMWARE_VER,
    
   CASE 
    WHEN DI = 'R' THEN 
        CASE 
            WHEN RT = 'R' THEN WRK_CENTER_ID
            WHEN AS_CMP_CAL_TST_RPRTD_JDGMNT = 'NOT_DONE' or AS_CMP_CAL_TST_RPRTD_JDGMNT = 'UNKNOWN' OR AS_CMP_CAL_TST_RPRTD_JDGMNT IS NULL THEN WRK_CENTER_ID
            ELSE AS_CMP_WRK_CENTER_ID
        END
    WHEN DI = 'C' THEN 
        CASE 
            WHEN RT = 'C' THEN AS_CMP_WRK_CENTER_ID
            WHEN CAL_TEST_RESLT_RPRTD_JDGMNT = 'NOT_DONE' OR CAL_TEST_RESLT_RPRTD_JDGMNT = 'UNKNOWN' OR CAL_TEST_RESLT_RPRTD_JDGMNT IS NULL THEN AS_CMP_WRK_CENTER_ID
            ELSE WRK_CENTER_ID
        END
    WHEN DI = 'A' OR DI = 'X' THEN
        CASE 
            WHEN RT = 'R' THEN WRK_CENTER_ID
            ELSE AS_CMP_WRK_CENTER_ID
        END
    ELSE 
        WRK_CENTER_ID
    END AS WRK_CENTER_ID,
  
    CASE 
    WHEN DI = 'R' THEN 
        CASE 
            WHEN RT = 'R' THEN APP_VER_NUM
            WHEN AS_CMP_CAL_TST_RPRTD_JDGMNT = 'NOT_DONE' or AS_CMP_CAL_TST_RPRTD_JDGMNT = 'UNKNOWN' OR AS_CMP_CAL_TST_RPRTD_JDGMNT IS NULL THEN APP_VER_NUM
            ELSE AS_CMP_APP_VER_NUM
        END
    WHEN DI = 'C' THEN 
        CASE 
            WHEN RT = 'C' THEN AS_CMP_APP_VER_NUM
            WHEN CAL_TEST_RESLT_RPRTD_JDGMNT = 'NOT_DONE' OR CAL_TEST_RESLT_RPRTD_JDGMNT = 'UNKNOWN' OR CAL_TEST_RESLT_RPRTD_JDGMNT IS NULL THEN AS_CMP_APP_VER_NUM
            ELSE APP_VER_NUM
        END
    WHEN DI = 'A' OR DI = 'X' THEN
        CASE 
            WHEN RT = 'R' THEN APP_VER_NUM
            ELSE AS_CMP_APP_VER_NUM
        END
    ELSE 
        APP_VER_NUM
    END AS APP_VER_NUM,
    
    CASE 
    WHEN DI = 'R' THEN 
        CASE 
            WHEN RT = 'R' THEN APP_ID
            WHEN AS_CMP_CAL_TST_RPRTD_JDGMNT = 'NOT_DONE' or AS_CMP_CAL_TST_RPRTD_JDGMNT = 'UNKNOWN' OR AS_CMP_CAL_TST_RPRTD_JDGMNT IS NULL THEN APP_ID
            ELSE AS_CMP_APP_ID
        END
    WHEN DI = 'C' THEN 
        CASE 
            WHEN RT = 'C' THEN AS_CMP_APP_ID
            WHEN CAL_TEST_RESLT_RPRTD_JDGMNT = 'NOT_DONE' OR CAL_TEST_RESLT_RPRTD_JDGMNT = 'UNKNOWN' OR CAL_TEST_RESLT_RPRTD_JDGMNT IS NULL THEN AS_CMP_APP_ID
            ELSE APP_ID
        END
    WHEN DI = 'A' OR DI = 'X' THEN
        CASE 
            WHEN RT = 'R' THEN APP_ID
            ELSE AS_CMP_APP_ID
        END
    ELSE 
        APP_ID
    END AS APP_ID,
    
    CASE 
    WHEN DI = 'R' THEN 
        CASE 
            WHEN RT = 'R' THEN APP_PLATFORM
            WHEN AS_CMP_CAL_TST_RPRTD_JDGMNT = 'NOT_DONE' or AS_CMP_CAL_TST_RPRTD_JDGMNT = 'UNKNOWN' OR AS_CMP_CAL_TST_RPRTD_JDGMNT IS NULL THEN APP_PLATFORM
            ELSE AS_CMP_APP_PLATFORM
        END
    WHEN DI = 'C' THEN 
        CASE 
            WHEN RT = 'C' THEN AS_CMP_APP_PLATFORM
            WHEN CAL_TEST_RESLT_RPRTD_JDGMNT = 'NOT_DONE' OR CAL_TEST_RESLT_RPRTD_JDGMNT = 'UNKNOWN' OR CAL_TEST_RESLT_RPRTD_JDGMNT IS NULL THEN AS_CMP_APP_PLATFORM
            ELSE APP_PLATFORM
        END
    WHEN DI = 'A' OR DI = 'X' THEN
        CASE 
            WHEN RT = 'R' THEN APP_PLATFORM
            ELSE AS_CMP_APP_PLATFORM
        END
    ELSE 
        APP_PLATFORM
    END AS APP_PLATFORM,
  
    CASE 
    WHEN DI = 'R' THEN 
        CASE 
            WHEN RT = 'R' THEN NEAR_SPCFCTN_LMT_IND
            WHEN AS_CMP_CAL_TST_RPRTD_JDGMNT = 'NOT_DONE' or AS_CMP_CAL_TST_RPRTD_JDGMNT = 'UNKNOWN' OR AS_CMP_CAL_TST_RPRTD_JDGMNT IS NULL THEN NEAR_SPCFCTN_LMT_IND
            ELSE AS_CMP_NEAR_SPCFCTN_LMT_IND
        END
    WHEN DI = 'C' THEN 
        CASE 
            WHEN RT = 'C' THEN AS_CMP_NEAR_SPCFCTN_LMT_IND
            WHEN CAL_TEST_RESLT_RPRTD_JDGMNT = 'NOT_DONE' OR CAL_TEST_RESLT_RPRTD_JDGMNT = 'UNKNOWN' OR CAL_TEST_RESLT_RPRTD_JDGMNT IS NULL THEN AS_CMP_NEAR_SPCFCTN_LMT_IND
            ELSE NEAR_SPCFCTN_LMT_IND
        END
    WHEN DI = 'A' OR DI = 'X' THEN
        CASE 
            WHEN RT = 'R' THEN NEAR_SPCFCTN_LMT_IND
            ELSE AS_CMP_NEAR_SPCFCTN_LMT_IND
        END
    ELSE 
        NEAR_SPCFCTN_LMT_IND
    END AS NEAR_SPCFCTN_LMT_IND,
  
    CASE 
    WHEN DI = 'R' THEN 
        CASE 
            WHEN RT = 'R' THEN NEAR_GURDBD_LMT_IND
            WHEN AS_CMP_CAL_TST_RPRTD_JDGMNT = 'NOT_DONE' or AS_CMP_CAL_TST_RPRTD_JDGMNT = 'UNKNOWN' OR AS_CMP_CAL_TST_RPRTD_JDGMNT IS NULL THEN NEAR_GURDBD_LMT_IND
            ELSE AS_CMP_NEAR_GURDBD_LMT_IND
        END
    WHEN DI = 'C' THEN 
        CASE 
            WHEN RT = 'C' THEN AS_CMP_NEAR_GURDBD_LMT_IND
            WHEN CAL_TEST_RESLT_RPRTD_JDGMNT = 'NOT_DONE' OR CAL_TEST_RESLT_RPRTD_JDGMNT = 'UNKNOWN' OR CAL_TEST_RESLT_RPRTD_JDGMNT IS NULL THEN AS_CMP_NEAR_GURDBD_LMT_IND
            ELSE NEAR_GURDBD_LMT_IND
        END
    WHEN DI = 'A' OR DI = 'X' THEN
        CASE 
            WHEN RT = 'R' THEN NEAR_GURDBD_LMT_IND
            ELSE AS_CMP_NEAR_GURDBD_LMT_IND
        END
    ELSE 
        NEAR_GURDBD_LMT_IND
    END AS NEAR_GURDBD_LMT_IND,
    
    CAL_TEST_DATA_TYP_ID,
    //UNCRTNTY_STAT_VAL,
    
    CASE 
    WHEN DI = 'R' THEN 
        CASE 
            WHEN RT = 'R' THEN UNCRTNTY_STAT_VAL
            WHEN AS_CMP_CAL_TST_RPRTD_JDGMNT = 'NOT_DONE' or AS_CMP_CAL_TST_RPRTD_JDGMNT = 'UNKNOWN' OR AS_CMP_CAL_TST_RPRTD_JDGMNT IS NULL THEN UNCRTNTY_STAT_VAL
            ELSE AS_CMP_UNCRTNTY_STAT_VAL
        END
    WHEN DI = 'C' THEN 
        CASE 
            WHEN RT = 'C' THEN AS_CMP_UNCRTNTY_STAT_VAL
            WHEN CAL_TEST_RESLT_RPRTD_JDGMNT = 'NOT_DONE' OR CAL_TEST_RESLT_RPRTD_JDGMNT = 'UNKNOWN' OR CAL_TEST_RESLT_RPRTD_JDGMNT IS NULL THEN AS_CMP_UNCRTNTY_STAT_VAL
            ELSE UNCRTNTY_STAT_VAL
        END
    WHEN DI = 'A' OR DI = 'X' THEN
        CASE 
            WHEN RT = 'R' THEN UNCRTNTY_STAT_VAL
            ELSE AS_CMP_UNCRTNTY_STAT_VAL
        END
    ELSE 
        UNCRTNTY_STAT_VAL
    END AS UNCRTNTY_STAT_VAL,
  
    CASE 
    WHEN DI = 'R' THEN 
        CASE 
            WHEN RT = 'R' THEN RPRTD_JDGMNT
            WHEN AS_CMP_CAL_TST_RPRTD_JDGMNT = 'NOT_DONE' or AS_CMP_CAL_TST_RPRTD_JDGMNT = 'UNKNOWN' OR AS_CMP_CAL_TST_RPRTD_JDGMNT IS NULL THEN RPRTD_JDGMNT
            ELSE AS_CMP_RPRTD_JDGMNT
        END
    WHEN DI = 'C' THEN 
        CASE 
            WHEN RT = 'C' THEN AS_CMP_RPRTD_JDGMNT
            WHEN CAL_TEST_RESLT_RPRTD_JDGMNT = 'NOT_DONE' OR CAL_TEST_RESLT_RPRTD_JDGMNT = 'UNKNOWN' OR CAL_TEST_RESLT_RPRTD_JDGMNT IS NULL THEN AS_CMP_RPRTD_JDGMNT
            ELSE RPRTD_JDGMNT
        END
    WHEN DI = 'A' OR DI = 'X' THEN
        CASE 
            WHEN RT = 'R' THEN RPRTD_JDGMNT
            ELSE AS_CMP_RPRTD_JDGMNT
        END
    ELSE 
        RPRTD_JDGMNT
    END AS RPRTD_JDGMNT,
    
    CASE 
    WHEN DI = 'R' THEN 
        CASE 
            WHEN RT = 'R' THEN STD_JDGMNT
            WHEN AS_CMP_CAL_TST_STD_JDGMNT = 'NOT_DONE' or AS_CMP_CAL_TST_STD_JDGMNT = 'UNKNOWN' OR AS_CMP_CAL_TST_STD_JDGMNT IS NULL THEN STD_JDGMNT
            ELSE AS_CMP_STD_JDGMNT
        END
    WHEN DI = 'C' THEN 
        CASE 
            WHEN RT = 'C' THEN AS_CMP_STD_JDGMNT
            WHEN CAL_TEST_RESLT_STD_JDGMNT = 'NOT_DONE' OR CAL_TEST_RESLT_STD_JDGMNT = 'UNKNOWN' OR CAL_TEST_RESLT_STD_JDGMNT IS NULL THEN AS_CMP_STD_JDGMNT
            ELSE STD_JDGMNT
        END
    WHEN DI = 'A' OR DI = 'X' THEN
        CASE 
            WHEN RT = 'R' THEN STD_JDGMNT
            ELSE AS_CMP_STD_JDGMNT
        END
    ELSE 
        STD_JDGMNT
    END AS STD_JDGMNT,
    
    CASE 
    WHEN DI = 'R' THEN 
        CASE 
            WHEN RT = 'R' THEN GURDBD_JDGMNT
            WHEN AS_CMP_CAL_TST_GURDBD_JDGMNT = 'NOT_DONE' or AS_CMP_CAL_TST_GURDBD_JDGMNT = 'UNKNOWN' OR AS_CMP_CAL_TST_GURDBD_JDGMNT IS NULL THEN GURDBD_JDGMNT
            ELSE AS_CMP_GURDBD_JDGMNT
        END
    WHEN DI = 'C' THEN 
        CASE 
            WHEN RT = 'C' THEN AS_CMP_GURDBD_JDGMNT
            WHEN CAL_TEST_RESLT_GURDBD_JDGMNT = 'NOT_DONE' OR CAL_TEST_RESLT_GURDBD_JDGMNT = 'UNKNOWN' OR CAL_TEST_RESLT_GURDBD_JDGMNT IS NULL THEN AS_CMP_GURDBD_JDGMNT
            ELSE GURDBD_JDGMNT
        END
    WHEN DI = 'A' OR DI = 'X' THEN
        CASE 
            WHEN RT = 'R' THEN GURDBD_JDGMNT
            ELSE AS_CMP_GURDBD_JDGMNT
        END
    ELSE 
        GURDBD_JDGMNT
    END AS GURDBD_JDGMNT,
    
    CASE 
    WHEN DI = 'R' THEN 
        CASE 
            WHEN RT = 'R' THEN PRCSS_JDGMNT
            WHEN AS_CMP_CAL_TST_PRCSS_JDGMNT = 'NOT_DONE' or AS_CMP_CAL_TST_PRCSS_JDGMNT = 'UNKNOWN' OR AS_CMP_CAL_TST_PRCSS_JDGMNT IS NULL THEN PRCSS_JDGMNT
            ELSE AS_CMP_PRCSS_JDGMNT
        END
    WHEN DI = 'C' THEN 
        CASE 
            WHEN RT = 'C' THEN AS_CMP_PRCSS_JDGMNT
            WHEN CAL_TEST_RESLT_PRCSS_JDGMNT = 'NOT_DONE' OR CAL_TEST_RESLT_PRCSS_JDGMNT = 'UNKNOWN' OR CAL_TEST_RESLT_PRCSS_JDGMNT IS NULL THEN AS_CMP_PRCSS_JDGMNT
            ELSE PRCSS_JDGMNT
        END
    WHEN DI = 'A' OR DI = 'X' THEN
        CASE 
            WHEN RT = 'R' THEN PRCSS_JDGMNT
            ELSE AS_CMP_PRCSS_JDGMNT
        END
    ELSE 
        PRCSS_JDGMNT
    END AS PRCSS_JDGMNT,
    
    INSERT_DT,
    UPD_DT,
    CXKEY_SRVC_ORD_NUM,
	LAST_MODIFIED_DT,
	CXKEY_CAL_PROCEDURE_ID,
	CXKEY_MFGR_ID,
	CXKEY_MFGR_MDL_NUM,
	CXKEY_SR_NUM,
	CXKEY_FRMWRK_ID,
	CXKEY_SUBMITTING_ENTITY,
	RESLT_TYP_DATAIS_COPY,
  
    CASE 
    WHEN DI = 'R' THEN 
        CASE 
            WHEN RT = 'R' THEN AS_CMP_CAL_TST_RPRTD_JDGMNT
            WHEN AS_CMP_CAL_TST_PRCSS_JDGMNT = 'NOT_DONE' or AS_CMP_CAL_TST_PRCSS_JDGMNT = 'UNKNOWN' OR AS_CMP_CAL_TST_PRCSS_JDGMNT IS NULL THEN AS_CMP_CAL_TST_RPRTD_JDGMNT
            ELSE AS_CMP_CAL_TST_RPRTD_JDGMNT
        END
    WHEN DI = 'C' THEN 
        CASE 
            WHEN RT = 'C' THEN AS_CMP_CAL_TST_RPRTD_JDGMNT
            WHEN CAL_TEST_RESLT_PRCSS_JDGMNT = 'NOT_DONE' OR CAL_TEST_RESLT_PRCSS_JDGMNT = 'UNKNOWN' OR CAL_TEST_RESLT_PRCSS_JDGMNT IS NULL THEN AS_CMP_CAL_TST_RPRTD_JDGMNT
            ELSE AS_CMP_CAL_TST_RPRTD_JDGMNT
        END
    WHEN DI = 'A' OR DI = 'X' THEN
        CASE 
            WHEN RT = 'R' THEN AS_CMP_CAL_TST_RPRTD_JDGMNT
            ELSE AS_CMP_CAL_TST_RPRTD_JDGMNT
        END
    ELSE 
        AS_CMP_CAL_TST_RPRTD_JDGMNT
    END AS CAL_TEST_RESLT_RPRTD_JDGMNT,
  
    CASE 
    WHEN DI = 'R' THEN 
        CASE 
            WHEN RT = 'R' THEN AS_CMP_CAL_TST_STD_JDGMNT
            WHEN AS_CMP_CAL_TST_PRCSS_JDGMNT = 'NOT_DONE' or AS_CMP_CAL_TST_PRCSS_JDGMNT = 'UNKNOWN' OR AS_CMP_CAL_TST_PRCSS_JDGMNT IS NULL THEN AS_CMP_CAL_TST_STD_JDGMNT
            ELSE AS_CMP_CAL_TST_STD_JDGMNT
        END
    WHEN DI = 'C' THEN 
        CASE 
            WHEN RT = 'C' THEN AS_CMP_CAL_TST_STD_JDGMNT
            WHEN CAL_TEST_RESLT_PRCSS_JDGMNT = 'NOT_DONE' OR CAL_TEST_RESLT_PRCSS_JDGMNT = 'UNKNOWN' OR CAL_TEST_RESLT_PRCSS_JDGMNT IS NULL THEN AS_CMP_CAL_TST_STD_JDGMNT
            ELSE AS_CMP_CAL_TST_STD_JDGMNT
        END
    WHEN DI = 'A' OR DI = 'X' THEN
        CASE 
            WHEN RT = 'R' THEN AS_CMP_CAL_TST_STD_JDGMNT
            ELSE AS_CMP_CAL_TST_STD_JDGMNT
        END
    ELSE 
        AS_CMP_CAL_TST_STD_JDGMNT
    END AS CAL_TEST_RESLT_STD_JDGMNT,
    
    CASE 
    WHEN DI = 'R' THEN 
        CASE 
            WHEN RT = 'R' THEN AS_CMP_CAL_TST_GURDBD_JDGMNT
            WHEN AS_CMP_CAL_TST_PRCSS_JDGMNT = 'NOT_DONE' or AS_CMP_CAL_TST_PRCSS_JDGMNT = 'UNKNOWN' OR AS_CMP_CAL_TST_PRCSS_JDGMNT IS NULL THEN AS_CMP_CAL_TST_GURDBD_JDGMNT
            ELSE AS_CMP_CAL_TST_GURDBD_JDGMNT
        END
    WHEN DI = 'C' THEN 
        CASE 
            WHEN RT = 'C' THEN AS_CMP_CAL_TST_GURDBD_JDGMNT
            WHEN CAL_TEST_RESLT_PRCSS_JDGMNT = 'NOT_DONE' OR CAL_TEST_RESLT_PRCSS_JDGMNT = 'UNKNOWN' OR CAL_TEST_RESLT_PRCSS_JDGMNT IS NULL THEN AS_CMP_CAL_TST_GURDBD_JDGMNT
            ELSE AS_CMP_CAL_TST_GURDBD_JDGMNT
        END
    WHEN DI = 'A' OR DI = 'X' THEN
        CASE 
            WHEN RT = 'R' THEN AS_CMP_CAL_TST_GURDBD_JDGMNT
            ELSE AS_CMP_CAL_TST_GURDBD_JDGMNT
        END
    ELSE 
        AS_CMP_CAL_TST_GURDBD_JDGMNT
    END AS CAL_TEST_RESLT_GURDBD_JDGMNT,
    
    CASE 
    WHEN DI = 'R' THEN 
        CASE 
            WHEN RT = 'R' THEN AS_CMP_CAL_TST_PRCSS_JDGMNT
            WHEN AS_CMP_CAL_TST_PRCSS_JDGMNT = 'NOT_DONE' or AS_CMP_CAL_TST_PRCSS_JDGMNT = 'UNKNOWN' OR AS_CMP_CAL_TST_PRCSS_JDGMNT IS NULL THEN AS_CMP_CAL_TST_PRCSS_JDGMNT
            ELSE AS_CMP_CAL_TST_PRCSS_JDGMNT
        END
    WHEN DI = 'C' THEN 
        CASE 
            WHEN RT = 'C' THEN AS_CMP_CAL_TST_PRCSS_JDGMNT
            WHEN CAL_TEST_RESLT_PRCSS_JDGMNT = 'NOT_DONE' OR CAL_TEST_RESLT_PRCSS_JDGMNT = 'UNKNOWN' OR CAL_TEST_RESLT_PRCSS_JDGMNT IS NULL THEN AS_CMP_CAL_TST_PRCSS_JDGMNT
            ELSE AS_CMP_CAL_TST_PRCSS_JDGMNT
        END
    WHEN DI = 'A' OR DI = 'X' THEN
        CASE 
            WHEN RT = 'R' THEN AS_CMP_CAL_TST_PRCSS_JDGMNT
            ELSE AS_CMP_CAL_TST_PRCSS_JDGMNT
        END
    ELSE 
        AS_CMP_CAL_TST_PRCSS_JDGMNT
    END AS CAL_TEST_RESLT_PRCSS_JDGMNT,
    
    CASE 
  WHEN DI = 'R' THEN 
    CASE 
      WHEN RT = 'R' THEN CAL_TST_RSLT_NR_SPFTN_LMT_IND 
      WHEN AS_CMP_CAL_TST_RPRTD_JDGMNT = 'NOT_DONE' OR AS_CMP_CAL_TST_RPRTD_JDGMNT = 'UNKNOWN' OR AS_CMP_CAL_TST_RPRTD_JDGMNT IS NULL THEN CAL_TST_RSLT_NR_SPFTN_LMT_IND 
      ELSE AS_CMP_CAL_TST_NEAR_SPCFCTN_LMT_IND 
    END 
  WHEN DI = 'C' THEN 
    CASE 
      WHEN RT = 'C' THEN AS_CMP_CAL_TST_NEAR_SPCFCTN_LMT_IND 
      WHEN CAL_TEST_RESLT_RPRTD_JDGMNT = 'NOT_DONE' OR CAL_TEST_RESLT_RPRTD_JDGMNT = 'UNKNOWN' OR CAL_TEST_RESLT_RPRTD_JDGMNT IS NULL THEN AS_CMP_CAL_TST_NEAR_SPCFCTN_LMT_IND 
      ELSE CAL_TST_RSLT_NR_SPFTN_LMT_IND 
    END 
  WHEN DI = 'A' OR DI = 'X' THEN 
    CASE 
      WHEN RT = 'R' THEN CAL_TST_RSLT_NR_SPFTN_LMT_IND 
      ELSE AS_CMP_CAL_TST_NEAR_SPCFCTN_LMT_IND 
    END 
  ELSE CAL_TST_RSLT_NR_SPFTN_LMT_IND 
  END AS CAL_TST_RSLT_NR_SPFTN_LMT_IND,
  
  
  
  CASE 
  WHEN DI = 'R' THEN 
    CASE 
      WHEN RT = 'R' THEN CAL_TST_RSLT_NR_GRDBD_LMT_IND 
      WHEN AS_CMP_CAL_TST_RPRTD_JDGMNT = 'NOT_DONE' OR AS_CMP_CAL_TST_RPRTD_JDGMNT = 'UNKNOWN' OR AS_CMP_CAL_TST_RPRTD_JDGMNT IS NULL THEN CAL_TST_RSLT_NR_GRDBD_LMT_IND 
      ELSE AS_CMP_CAL_TST_NEAR_GURDBD_LMT_IND 
    END 
  WHEN DI = 'C' THEN 
    CASE 
      WHEN RT = 'C' THEN AS_CMP_CAL_TST_NEAR_GURDBD_LMT_IND 
      WHEN CAL_TEST_RESLT_RPRTD_JDGMNT = 'NOT_DONE' OR CAL_TEST_RESLT_RPRTD_JDGMNT = 'UNKNOWN' OR CAL_TEST_RESLT_RPRTD_JDGMNT IS NULL THEN AS_CMP_CAL_TST_NEAR_GURDBD_LMT_IND 
      ELSE CAL_TST_RSLT_NR_GRDBD_LMT_IND 
    END 
  WHEN DI = 'A' OR DI = 'X' THEN 
    CASE 
      WHEN RT = 'R' THEN CAL_TST_RSLT_NR_GRDBD_LMT_IND 
      ELSE AS_CMP_CAL_TST_NEAR_GURDBD_LMT_IND 
    END 
  ELSE CAL_TST_RSLT_NR_GRDBD_LMT_IND 
  END AS CAL_TST_RSLT_NR_GRDBD_LMT_IND

  from stg
 ),
 
lkp as (
    
    select 
    RPRTD_JDGMNT,
    STD_JDGMNT,
    GURDBD_JDGMNT,
    PRCSS_JDGMNT,
    NEAR_SPCFCTN_LMT_IND,
    NEAR_GURDBD_LMT_IND,
    CAL_CONTXT_ID,
    TRY_TO_TIMESTAMP(TEST_ST_TIME) as TEST_ST_TIME,
    TRY_TO_TIMESTAMP(TEST_END_TIME) as TEST_END_TIME,
    STTN_NM,
    REPRT_NM,
    APP_VER_NUM,
    UNCRTNTY_STAT_VAL,
    WRK_CENTER_ID,
    FIRMWARE_VER,
    LMTED_TUR,
    ADJSTD_CVRG_FACTOR as COVERAGE_FACTOR,
    CAL_DT,
    CUST_ID,
    UNT_ID,
    SRVC_PRVDR_ID,
    stg.CXKEY_SRVC_ORD_NUM,
    TRY_TO_TIMESTAMP(stg.LAST_MODIFIED_DT) as LAST_MODIFIED_DT,
    CAL_PROCEDURE_ID,
    stg.CXKEY_CAL_PROCEDURE_ID,
    stg.CXKEY_MFGR_ID,
    stg.CXKEY_MFGR_MDL_NUM,
    stg.CXKEY_SR_NUM,
    stg.CXKEY_FRMWRK_ID,
    stg.CXKEY_SUBMITTING_ENTITY,
    stg.TEST_NM as CXKEY_CAL_TEST_RESLT_NM,
    RESLT_TYP as CXKEY_RESLT_TYP,
    APP_PLATFORM as CXKEY_APP_PLATFORM,
    APP_ID as CXKEY_APP_ID,
    RESLT_TYP_DATAIS_COPY,
    DI as ASRECDORCOMP_DATA_IND,
    CAL_TEST_RESLT_RPRTD_JDGMNT,
    CAL_TEST_RESLT_STD_JDGMNT,
	CAL_TEST_RESLT_GURDBD_JDGMNT,
	CAL_TEST_RESLT_PRCSS_JDGMNT,
	CAL_TST_RSLT_NR_SPFTN_LMT_IND,
	CAL_TST_RSLT_NR_GRDBD_LMT_IND
  
    from expr_111 stg
    left outer join CA_CAL_SRVC_RESLT_FACT fact ON
    stg.CXKEY_SRVC_ORD_NUM =  fact.CXKEY_SRVC_ORD_NUM AND
    stg.CXKEY_CAL_PROCEDURE_ID =  fact.CXKEY_CAL_PROCEDURE_ID AND
    stg.CXKEY_MFGR_MDL_NUM =  fact.CXKEY_MFGR_MDL_NUM AND
    stg.CXKEY_SR_NUM =  fact.CXKEY_SR_NUM AND
    stg.CXKEY_FRMWRK_ID =  fact.CXKEY_FRMWRK_ID AND
    stg.CXKEY_SUBMITTING_ENTITY =  fact.CXKEY_SUBMITTING_ENTITY AND
    stg.LAST_MODIFIED_DT =  fact.LAST_MODIFIED_DT
 ) select 
    distinct CA_CAL_TEST_RESLT_FACT_SEQ.nextval as CAL_TEST_RESLT_ID,*
    from lkp