 {{
    config(
        materialized='incremental',
        unique_key=['CXKEY_HDR_COMMNT', 'TEST_DATA_SCTN_ID']
    )
}}

with final as (
select 
    STG.CXKEY_HDR_COMMNT,
	TGT.TEST_DATA_SCTN_ID,
	STG.CXKEY_SRVC_ORD_NUM,
	STG.LAST_MODIFIED_DT,
	STG.CXKEY_CAL_PROCEDURE_ID,
	STG.CXKEY_MFGR_ID,
	STG.CXKEY_MFGR_MDL_NUM,
	STG.CXKEY_SR_NUM,
	STG.CXKEY_FRMWRK_ID,
	STG.CXKEY_SUBMITTING_ENTITY,
	STG.CXKEY_APP_PLATFORM,
	STG.CXKEY_APP_ID,
	STG.CXKEY_CAL_TEST_RESLT_NM,
	STG.CXKEY_CAL_TEST_RESLT_TYP,
	STG.CXKEY_CAL_TEST_DATA_ID,
	STG.CXKEY_TEST_DATA_SCTN_NM
    from {{ ref('ca_test_data_sctn_hdr_stg') }} STG
    LEFT OUTER JOIN 
    CA_TEST_DATA_SCTN TGT      
    ON 
    STG.CXKEY_TEST_DATA_SCTN_NM = TGT.CXKEY_TEST_DATA_SCTN_NM AND
    STG.CXKEY_SRVC_ORD_NUM = TGT.CXKEY_SRVC_ORD_NUM AND
    STG.LAST_MODIFIED_DT = TGT.LAST_MODIFIED_DT AND
    STG.CXKEY_CAL_PROCEDURE_ID = TGT.CXKEY_CAL_PROCEDURE_ID AND
    STG.CXKEY_MFGR_ID = TGT.CXKEY_MFGR_ID AND
    STG.CXKEY_MFGR_MDL_NUM =  TGT.CXKEY_MFGR_MDL_NUM AND
    STG.CXKEY_SR_NUM = TGT.CXKEY_SR_NUM AND
    STG.CXKEY_FRMWRK_ID = TGT.CXKEY_FRMWRK_ID AND
    STG.CXKEY_SUBMITTING_ENTITY = TGT.CXKEY_SUBMITTING_ENTITY AND
    STG.CXKEY_CAL_TEST_RESLT_NM  = TGT.CXKEY_CAL_TEST_RESLT_NM AND
    STG.CXKEY_CAL_TEST_RESLT_TYP  = TGT.CXKEY_CAL_TEST_RESLT_TYP AND
    STG.CXKEY_APP_PLATFORM  = TGT.CXKEY_APP_PLATFORM AND
    STG.CXKEY_APP_ID  = TGT.CXKEY_APP_ID
  
)
  select distinct
  CXKEY_HDR_COMMNT,
  TEST_DATA_SCTN_ID,
  CXKEY_SRVC_ORD_NUM,
  LAST_MODIFIED_DT,
  CXKEY_CAL_PROCEDURE_ID,
  CXKEY_MFGR_ID,
  CXKEY_MFGR_MDL_NUM,
  CXKEY_SR_NUM,
  CXKEY_FRMWRK_ID,
  CXKEY_SUBMITTING_ENTITY,
  CXKEY_APP_PLATFORM,
  CXKEY_APP_ID,
  CXKEY_CAL_TEST_RESLT_NM,
  CXKEY_CAL_TEST_RESLT_TYP ,
  CXKEY_CAL_TEST_DATA_ID,
  CXKEY_TEST_DATA_SCTN_NM
  from final
  where TEST_DATA_SCTN_ID is not null or TEST_DATA_SCTN_ID = to_decimal('')